### ISSUE TITLE
Still doesn't work without `:setf sile` (maybe only in normal `vim`)

### ISSUE THREAD

**Issue by ctrlcctrlv** [alerque/vim-sile#7]
Making an open issue so https://github.com/sile-typesetter/vim-sile/issues/4#issuecomment-1037296729 doesn't get lost.

I ran `git reset --hard` in `/home/fred/.vim/bundle/vim-sile/` to wipe my changes, then within vim `:VundleUpdate`, restart vim, still had to apply the <kbd>!</kbd> patch above.

**Comment by 14mRh4X0r** [comment]
Vim's own filetype detection sets the format to Swift Intermediate Language for *.sil, see https://github.com/vim/vim/blob/6e28703a8e41f775f64e442c5d11ce1ff599aa3f/runtime/filetype.vim#L1865-L1866

Seeing how this plugin needs to be installed explicitly, `setf sile` could probably be replaced with a plain `set ft=sile`.

**Comment by alerque** [comment]
I figured out how to repro this.

Here is the real trouble:

https://github.com/vim/vim/commit/0d76683e094c6cac2e879601aff3acf1163cbe0b

Our use of '*.sil' and this VIM filetype considerably predate (by 5 years) VIM's addition of "Swift Intermediate Language", whatever that is. We're either going to need to be more aggressive or setup heuristics.

**Comment by alerque** [comment]
As @14mRh4X0r suggested I just aggressively reclaimed the extension from upstream VIM's ideas. If anybody actually needs Swift Intermediate support to play nice we can try to come up with a content snooping heuristic instead.

Also I feel kind of dumb because the whole conf/modula2 dodge was blindly copy/pasted from a syntax plugin that had to work around a problem with Markdown file type issues. It doesn't serve anything for this case. :man_shrugging:

**Comment by ctrlcctrlv** [comment]
> As @14mRh4X0r suggested I just aggressively reclaimed the extension from upstream VIM's ideas. If anybody actually needs Swift Intermediate support to play nice we can try to come up with a content snooping heuristic instead.

I tend to be the aggressive one :wink: so leave it to me: https://github.com/vim/vim/issues/10974
